port 26381
bind 0.0.0.0
# Replace 172.18.0.2 with the result from the 'inspect' command above
sentinel monitor mymaster 172.20.0.2 6380 2
sentinel announce-ip 127.0.0.1
sentinel announce-port 26381
sentinel failover-timeout mymaster 10000
sentinel down-after-milliseconds mymaster 5000